CREATE TABLE promotion (
PromotionID INT(11) AUTO_INCREMENT PRIMARY KEY,
PromotionName VARCHAR(100),
Reward VARCHAR(300) NOT NULL,
Redeem_condition VARCHAR(300),
Point INT(5),
Image VARCHAR(300)
)DEFAULT CHARSET=utf8;


CREATE TABLE code (
CodeID INT(11) AUTO_INCREMENT PRIMARY KEY,
CodeName VARCHAR(100) NOT NULL,
CodeType VARCHAR(100) NOT NULL,
CodePoint INT(11) NOT NULL
)DEFAULT CHARSET=utf8;

CREATE TABLE codeUsed (
AccountID VARCHAR(13) NOT NULL, 
CodeID INT(11) NOT NULL,
PointEarn INT(11) NOT NULL
)DEFAULT CHARSET=utf8;
